baseURL = "https://sadikozel.github.io/"
title = "Sadık ÖZEL"
theme = "hugo-noir"

relativeURLs = true
canonifyURLs = true
defaultContentLanguage = "tr"
defaultContentLanguageInSubdir = true
disableKinds = ["taxonomy", "term"]

[languages]
  [languages.tr]
    languageName = "Türkçe"
    weight = 1
    contentDir = "content/tr"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    