baseURL = "https://sadikozel.github.io/"
title = "Sadık ÖZEL"
theme = "hugo-noir"

relativeURLs = true
canonifyURLs = true
defaultContentLanguage = "tr"
defaultContentLanguageInSubdir = true
disableKinds = ["taxonomy", "term"]

[params]
name = "Sadık ÖZEL"
location = "Aksaray, TR"
github = "https://github.com/sadikozel"
github_username = "sadikozel"
email = "sadik.ozel@hotmail.com"
linkedin = "https://www.linkedin.com/in/sadikozel"
linkedin_username = "sadikozel"


[languages]
  [languages.tr]
    languageName = "Türkçe"
    weight = 1
    contentDir = "content/tr"
        [languages.tr.menu]
            [[languages.tr.menu.main]]
                name = "Hakkımda"
                pageRef = "/about"
                weight = 1
            [[languages.tr.menu.main]]
                name = "Deneyimler"
                pageRef = "/experience"
                weight = 2
            [[languages.tr.menu.main]]
                name = "İletişim"
                pageRef = "/contact"
                weight = 3

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "About"
                pageRef = "/about"
                weight = 1
            [[languages.en.menu.main]]
                name = "Experience"
                pageRef = "/experience"
                weight = 2
            [[languages.en.menu.main]]
                name = "Contact"
                pageRef = "/contact"
                weight = 3